<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSp1rvkq\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSp1rvkq/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerSp1rvkq.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerSp1rvkq\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerSp1rvkq\appProdProjectContainer([
    'container.build_hash' => 'Sp1rvkq',
    'container.build_id' => '45509a21',
    'container.build_time' => 1581992706,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSp1rvkq');
